-- MySQL Script generated by MySQL Workbench
-- Wed Apr 16 23:04:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

use startup_battle;

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET collation_connection = 'utf8mb4_0900_ai_ci';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema startup_battle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `startup_battle` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `startup_battle` ;

-- -----------------------------------------------------
-- Table `startup_battle`.`Startup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `startup_battle`.`Startup` ;

CREATE TABLE IF NOT EXISTS `startup_battle`.`Startup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `slogan` VARCHAR(255) NOT NULL,
  `year_foundation` INT NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`)) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_battle`.`Tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `startup_battle`.`Tournament` ;

CREATE TABLE IF NOT EXISTS `startup_battle`.`Tournament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('ongoing', 'done') NULL DEFAULT 'ongoing',
  `qty_startups` INT NOT NULL,
  `qty_rounds` INT NOT NULL,
  `champion_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `champion_id_idx` (`champion_id` ASC) VISIBLE,
  CONSTRAINT `champion_id_fk`
    FOREIGN KEY (`champion_id`)
    REFERENCES `startup_battle`.`Startup` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_battle`.`Round`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `startup_battle`.`Round` ;

CREATE TABLE IF NOT EXISTS `startup_battle`.`Round` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tournament_id` INT NOT NULL,
  `number` INT NOT NULL,
  `status` ENUM('pending', 'ongoing', 'done') NULL DEFAULT 'pending',
  PRIMARY KEY (`id`),
  INDEX `tournament_id_idx` (`tournament_id` ASC) VISIBLE,
  CONSTRAINT `tournament_id_fk`
    FOREIGN KEY (`tournament_id`)
    REFERENCES `startup_battle`.`Tournament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_battle`.`Battle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `startup_battle`.`Battle` ;

CREATE TABLE IF NOT EXISTS `startup_battle`.`Battle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `round_id` INT NOT NULL,
  `startup1_id` INT NOT NULL,
  `startup2_id` INT,
  `winner_id` INT NULL,
  `status` ENUM('pending', 'done') NULL DEFAULT 'pending',
  `shark_fight` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `round_id_idx` (`round_id` ASC) VISIBLE,
  INDEX `startup1_id_idx` (`startup1_id` ASC) VISIBLE,
  INDEX `startup2_id_idx` (`startup2_id` ASC) VISIBLE,
  INDEX `winner_id_idx` (`winner_id` ASC) VISIBLE,
  CONSTRAINT `round_id_fk`
    FOREIGN KEY (`round_id`)
    REFERENCES `startup_battle`.`Round` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `startup1_id_fk`
    FOREIGN KEY (`startup1_id`)
    REFERENCES `startup_battle`.`Startup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `startup2_id_fk`
    FOREIGN KEY (`startup2_id`)
    REFERENCES `startup_battle`.`Startup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `winner_id_fk`
    FOREIGN KEY (`winner_id`)
    REFERENCES `startup_battle`.`Startup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_battle`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `startup_battle`.`Event` ;

CREATE TABLE IF NOT EXISTS `startup_battle`.`Event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL,
  `impact_score` INT NOT NULL,
  PRIMARY KEY (`id`)) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `startup_battle`.`Event_battle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `startup_battle`.`Event_battle` ;

CREATE TABLE IF NOT EXISTS `startup_battle`.`Event_battle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `battle_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `startup_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `battle_id_idx` (`battle_id` ASC) VISIBLE,
  INDEX `startup_id_idx` (`startup_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `battle_id_fk`
    FOREIGN KEY (`battle_id`)
    REFERENCES `startup_battle`.`Battle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `startup_id_fk`
    FOREIGN KEY (`startup_id`)
    REFERENCES `startup_battle`.`Startup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `event_id_fk`
    FOREIGN KEY (`event_id`)
    REFERENCES `startup_battle`.`Event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Tabela `startup_battle`.`Startup_Statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `startup_battle`.`Startup_Statistics` ;

CREATE TABLE IF NOT EXISTS `startup_battle`.`Startup_Statistics` (
  `startup_id` INT NOT NULL,
  `total_pitches` INT NULL DEFAULT 0,
  `total_bugs` INT NULL DEFAULT 0,
  `total_traction` INT NULL DEFAULT 0,
  `total_pissed_investors` INT NULL DEFAULT 0,
  `total_fakenews` INT NULL DEFAULT 0,
  `total_sharkfights` INT NULL DEFAULT 0,
  `total_wins` INT NULL DEFAULT 0,
  PRIMARY KEY (`startup_id`),
  CONSTRAINT `startup_id_fk_1`
    FOREIGN KEY (`startup_id`)
    REFERENCES `startup_battle`.`Startup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela `startup_battle`.`Startup_tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `startup_battle`.`Startup_tournament` ;

CREATE TABLE IF NOT EXISTS `startup_battle`.`Startup_tournament` (
  `startup_id` INT NOT NULL,
  `tournament_id` INT NOT NULL,
  `score` INT NULL DEFAULT 70,
  INDEX `startup_id_idx` (`startup_id` ASC) VISIBLE,
  INDEX `tournament_id_idx` (`tournament_id` ASC) VISIBLE,
  CONSTRAINT `startup_id_fk_2`
    FOREIGN KEY (`startup_id`)
    REFERENCES `startup_battle`.`Startup` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tournament_id_fk1`
    FOREIGN KEY (`tournament_id`)
    REFERENCES `startup_battle`.`Tournament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
ENGINE = InnoDB;

INSERT INTO `startup_battle`.`Event` (`name`, `description`, `impact_score`)
VALUES 
('Pitch convincente', 'Um pitch muito cativante', 6),
('Produto com bugs', 'Independente de ser bom ou não apresenta bugs :(', -4),
('Boa tração de usuários', 'O favorito de qualquer frontender', 3),
('Investidor irritado', 'Se passou...', -6),
('Fake news', 'Po mas aí ta de brincadeira', -8);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
