# Generated by Django 5.2 on 2025-04-17 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=7)),
                ('shark_fight', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Battle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('impact_score', models.IntegerField()),
            ],
            options={
                'db_table': 'Event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'EventBattle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='pending', max_length=8)),
            ],
            options={
                'db_table': 'Round',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=255)),
                ('year_foundation', models.IntegerField()),
                ('score', models.IntegerField(blank=True, default=70, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Startup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('done', 'Done')], default='ongoing', max_length=7)),
            ],
            options={
                'db_table': 'Tournament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StartupStatistics',
            fields=[
                ('startup', models.OneToOneField(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='startups.startup')),
                ('total_pitches', models.IntegerField(blank=True, default=0, null=True)),
                ('total_bugs', models.IntegerField(blank=True, default=0, null=True)),
                ('total_traction', models.IntegerField(blank=True, default=0, null=True)),
                ('total_pissed_investors', models.IntegerField(blank=True, default=0, null=True)),
                ('total_fakenews', models.IntegerField(blank=True, default=0, null=True)),
                ('total_sharkfights', models.IntegerField(blank=True, default=0, null=True)),
                ('total_wins', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'StartupStatistics',
                'managed': False,
            },
        ),
    ]
