# Generated by Django 5.2 on 2025-04-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startuptournament'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Battle',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventBattle',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='StartupTournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
