# Generated by Django 5.2 on 2025-04-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_delete_battle_delete_event_delete_eventbattle_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='startupstatistics',
            table='Startup_Statistics',
        ),
    ]
