# Generated by Django 5.2 on 2025-04-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=7)),
                ('shark_fight', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Battle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventBattle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'EventBattle',
                'managed': False,
            },
        ),
    ]
