# Generated by Django 5.2 on 2025-04-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventbattle',
            table='Event_battle',
        ),
    ]
