# Generated by Django 5.2 on 2025-04-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_alter_eventbattle_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('impact_score', models.IntegerField()),
            ],
            options={
                'db_table': 'Event',
                'managed': False,
            },
        ),
    ]
