# Generated by Django 5.2 on 2025-04-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=70, null=True)),
            ],
            options={
                'db_table': 'Startup_tournament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('done', 'Done')], default='ongoing', max_length=7)),
                ('qty_startups', models.IntegerField()),
                ('qty_rounds', models.IntegerField()),
            ],
            options={
                'db_table': 'Tournament',
                'managed': False,
            },
        ),
    ]
