# Generated by Django 5.2 on 2025-04-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='pending', max_length=8)),
            ],
            options={
                'db_table': 'Round',
                'managed': False,
            },
        ),
    ]
